### ISSUE TITLE
可否把本项目精简，或者单独独立出一个生成数据字典项目

### ISSUE THREAD

**Issue by star7th** [whaios/goshowdoc#2]
你这个项目很棒，我打算在引入showdoc官方教程里。原来的官方脚本showdoc_db.sh将会继续支持mysql，如果想要支持SQLServer，PostgreSQL等数据库则推荐使用你的库。
不过有个问题，由于官方的showdoc_api.sh脚本已经支持runapi项目(见文档说明 https://www.showdoc.com.cn/page/741656402509783 ) ，所以你在goshowdoc里介绍的api文档生成方式并不被官方推荐，如果我推荐你的话，会容易误导用户。所以我建议可否把本项目精简，去掉生成runapi文档功能，或者把生成数据字典功能单独放出来做成另一个独立项目。生成数据字典这块，官方不打算自己支持了。因为要测试各种数据库，挺麻烦的，而且使用用户群也没有很多，干脆就直接由第三方库支持了。

**Comment by whaios** [comment]
> 

可以独立出来做一个项目

**Comment by whaios** [comment]
> 你这个项目很棒，我打算在引入showdoc官方教程里。原来的官方脚本showdoc_db.sh将会继续支持mysql，如果想要支持SQLServer，PostgreSQL等数据库则推荐使用你的库。 不过有个问题，由于官方的showdoc_api.sh脚本已经支持runapi项目(见文档说明 https://www.showdoc.com.cn/page/741656402509783 ) ，所以你在goshowdoc里介绍的api文档生成方式并不被官方推荐，如果我推荐你的话，会容易误导用户。所以我建议可否把本项目精简，去掉生成runapi文档功能，或者把生成数据字典功能单独放出来做成另一个独立项目。生成数据字典这块，官方不打算自己支持了。因为要测试各种数据库，挺麻烦的，而且使用用户群也没有很多，干脆就直接由第三方库支持了。

已经独立到 showdocdb 项目中 https://github.com/whaios/showdocdb
